import type { Metadata } from "next";
import "./globals.css";
import {  WalletContextProvider } from "@/context/Wallet";
import { Footer, Header } from "@/app/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletContextProvider>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </WalletContextProvider>
    </html>
  );
}
